# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LArYDCKgk7ujy7HfFzo3hq0kWtqFzWfN
"""

Month = int(input())
if Month == 1:
  print('January') 
elif Month == 2:
  print('February')
elif Month == 3:
  print('March')
elif Month == 4:
  print('April')
elif Month == 5:
  print('May')
elif Month == 6:
  print('June')
elif Month == 7:
  print('July')
elif Month == 8:
  print('August')
elif Month == 9:
  print('September')
elif Month == 10:
  print('October')
elif Month == 11:
  print('November')
elif Month == 12:
  print('December')
else: print(0)

N = int(input())
if (N % 2):
  print('нечетн')
else: 
  print('четн')

N = int(input())
if N > 48:
  print('stonks')
elif N < 48:
  print('not stonks')

def is_year_leap():
  year=int(input())
  if year % 4 != 0 or (year%100==0 and year%400 ==0):
    return False
  else:
    return True
is_year_leap()

def is_prime():
  n=int(input())
  a=False
  for i in range(2,n):
    if n%i==0:
      a=False
      break
    else:
      a=True
  return(a)
is_prime()

a=int(input())
b=int(input())  
if a/b>=3.6 or b in range ((-138/2)**1.3 and b>=abs((-69/28**5.1)*4)):
  a, b = b, a
print(a, b)